/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "#c0c1ff",
        "tertiary-fixed-dim": "#4edea3",
        "primary-fixed-dim": "#c0c1ff",
        "secondary-fixed": "#acedff",
        "on-surface": "#d4e4fa",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#005236",
        "secondary": "#4cd7f6",
        "tertiary": "#4edea3",
        "surface-dim": "#051424",
        "surface": "#051424",
        "on-tertiary": "#003824",
        "surface-bright": "#2c3a4c",
        "on-tertiary-fixed": "#002113",
        "surface-variant": "#273647",
        "surface-container-lowest": "#010f1f",
        "on-background": "#d4e4fa",
        "outline": "#908fa0",
        "secondary-container": "#03b5d3",
        "on-secondary-fixed": "#001f26",
        "surface-container-high": "#1c2b3c",
        "primary-fixed": "#e1e0ff",
        "primary": "#c0c1ff",
        "surface-container-highest": "#273647",
        "on-secondary-fixed-variant": "#004e5c",
        "primary-container": "#8083ff",
        "on-primary-fixed-variant": "#2f2ebe",
        "on-primary-container": "#0d0096",
        "on-primary": "#1000a9",
        "on-secondary-container": "#00424e",
        "on-secondary": "#003640",
        "error": "#ffb4ab",
        "error-container": "#93000a",
        "inverse-surface": "#d4e4fa",
        "on-surface-variant": "#c7c4d7",
        "inverse-on-surface": "#233143",
        "secondary-fixed-dim": "#4cd7f6",
        "inverse-primary": "#494bd6",
        "surface-container": "#122131",
        "on-primary-fixed": "#07006c",
        "surface-container-low": "#0d1c2d",
        "on-error": "#690005",
        "background": "#051424",
        "tertiary-fixed": "#6ffbbe",
        "tertiary-container": "#00885d",
        "outline-variant": "#464554",
        "on-tertiary-container": "#000703"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "3xl": "56px",
        "unit": "4px",
        "sm": "8px",
        "2xl": "40px",
        "lg": "20px",
        "gutter": "20px",
        "xs": "4px",
        "xl": "28px",
        "md": "12px",
        "margin": "20px"
      },
      fontFamily: {
        "display-3xl-mobile": ["Inter", "sans-serif"],
        "body-base": ["Inter", "sans-serif"],
        "display-3xl": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-xs": ["Inter", "sans-serif"],
        "display-2xl": ["Inter", "sans-serif"],
        "headline-xl": ["Inter", "sans-serif"]
      },
      fontSize: {
        "display-3xl-mobile": ["20px", { "lineHeight": "28px", "fontWeight": "700" }],
        "body-base": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "display-3xl": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg": ["16px", { "lineHeight": "24px", "fontWeight": "600" }],
        "label-sm": ["13px", { "lineHeight": "18px", "fontWeight": "500" }],
        "body-sm": ["13px", { "lineHeight": "18px", "fontWeight": "400" }],
        "label-xs": ["11px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "display-2xl": ["20px", { "lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "headline-xl": ["18px", { "lineHeight": "26px", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
